# See https://cloud.google.com/appengine/docs/flexible/nodejs/reference/app-yaml

runtime: nodejs
env: flex

handlers:
  # Image used in the QPE tutorial notebook in Challenges portal for QAL
  - url: /content/ch-algorithms/images/qpe_tex_qz.png
    static_files: content/v2/ch-algorithms/images/qpe_tex_qz.png
    upload: content/v2/ch-algorithms/images/qpe_tex_qz.png
    redirect_http_response_code: 301

  - url: /.*
    script: app.js
    secure: always

resources:
  cpu: 1
  memory_gb: 1

liveness_check:
  path: "/health"

readiness_check:
  path: "/health"
  app_start_timeout_sec: 600

env_variables:
  NODE_ENV: "production"
